// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dietsync.Models;

public partial class Contador
{
    public int? Contador1 { get; set; }
}