// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dietsync.Models;

public partial class DadosSessao
{
    public ulong IdLogin { get; set; }

    public ulong? FkIdUserLogin { get; set; }

    public DateTime? DataLogin { get; set; }

    public virtual User FkIdUserLoginNavigation { get; set; }
}