// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace dietsync.Models;

public partial class Evolucao
{
    public ulong Id { get; set; }

    public DateOnly Data { get; set; }

    public double Peso { get; set; }

    public double Altura { get; set; }

    public double Cintura { get; set; }

    public ulong? FkIdEvolucaos { get; set; }

    // public long FkIdUsuario { get; set; }

    public virtual User FkIdEvolucaosNavigation { get; set; }
}