// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
using dietsync.Domain.Entities;
namespace dietsync.Infrastructure.Data;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Contador> Contadors { get; set; }

    public virtual DbSet<DadosSessao> DadosSessaos { get; set; }

    public virtual DbSet<Dieta> Dietas { get; set; }

    public virtual DbSet<Evolucao> Evolucaos { get; set; }

    public virtual DbSet<Receitum> Receita { get; set; }

    public virtual DbSet<Treino> Treinos { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Contador>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("contador")
                .UseCollation("utf8mb4_unicode_ci");

            entity.Property(e => e.Contador1).HasColumnName("contador");
        });

        modelBuilder.Entity<DadosSessao>(entity =>
        {
            entity.HasKey(e => e.IdLogin).HasName("PRIMARY");

            entity.ToTable("dados_sessao");

            entity.HasIndex(e => e.FkIdUserLogin, "fk_id_user_login");

            entity.Property(e => e.IdLogin).HasColumnName("id_login");
            entity.Property(e => e.DataLogin)
                .HasColumnType("datetime")
                .HasColumnName("data_login");
            entity.Property(e => e.FkIdUserLogin).HasColumnName("fk_id_user_login");

            entity.HasOne(d => d.FkIdUserLoginNavigation).WithMany(p => p.DadosSessaos)
                .HasForeignKey(d => d.FkIdUserLogin)
                .HasConstraintName("fk_id_user_login");
        });

        modelBuilder.Entity<Dieta>(entity =>
        {
            entity.HasKey(e => e.IdDieta).HasName("PRIMARY");

            entity
                .ToTable("dietas")
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.FkIdUsuarioDieta, "dietas_ibfk_1");

            entity.Property(e => e.IdDieta).HasColumnName("id_dieta");
            entity.Property(e => e.Alimentos)
                .IsRequired()
                .HasColumnName("alimentos")
                .UseCollation("utf8mb4_bin");
            entity.Property(e => e.Calorias)
                .HasColumnType("double(8,2)")
                .HasColumnName("calorias");
            entity.Property(e => e.Carboidratos)
                .HasColumnType("double(8,2)")
                .HasColumnName("carboidratos");
            entity.Property(e => e.DataDieta)
                .IsRequired()
                .HasMaxLength(1)
                .IsFixedLength()
                .HasColumnName("data_dieta");
            entity.Property(e => e.FkIdUsuarioDieta).HasColumnName("fk_id_usuario_dieta");
            entity.Property(e => e.Gorduras)
                .HasColumnType("double(8,2)")
                .HasColumnName("gorduras");
            entity.Property(e => e.NomeDieta)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nome_dieta");
            entity.Property(e => e.Observacoes)
                .HasColumnType("text")
                .HasColumnName("observacoes");
            entity.Property(e => e.Proteinas)
                .HasColumnType("double(8,2)")
                .HasColumnName("proteinas");
            entity.Property(e => e.Quantidade).HasColumnName("quantidade");
            entity.Property(e => e.Refeicao)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("refeicao");
            entity.Property(e => e.TipoDieta)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("tipo_dieta");

            entity.HasOne(d => d.FkIdUsuarioDietaNavigation).WithMany(p => p.Dieta)
                .HasForeignKey(d => d.FkIdUsuarioDieta)
                .HasConstraintName("dietas_ibfk_1");
        });

        modelBuilder.Entity<Evolucao>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("evolucaos")
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.FkIdEvolucaos, "fk_id_evolucaos");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Altura)
                .HasColumnType("double(8,2)")
                .HasColumnName("altura");
            entity.Property(e => e.Cintura)
                .HasColumnType("double(8,2)")
                .HasColumnName("cintura");
            entity.Property(e => e.Data).HasColumnName("data");
            entity.Property(e => e.FkIdEvolucaos).HasColumnName("fk_id_evolucaos");
            // entity.Property(e => e.FkIdUsuario).HasColumnName("fk_id_usuario");
            entity.Property(e => e.Peso)
                .HasColumnType("double(8,2)")
                .HasColumnName("peso");

            entity.HasOne(d => d.FkIdEvolucaosNavigation).WithMany(p => p.Evolucaos)
                .HasForeignKey(d => d.FkIdEvolucaos)
                .HasConstraintName("fk_id_evolucaos");
        });

        modelBuilder.Entity<Receitum>(entity =>
        {
            entity.HasKey(e => e.IdReceitas).HasName("PRIMARY");

            entity
                .ToTable("receita")
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.FkIdUserReceita, "fk_id_user_receita");

            entity.Property(e => e.IdReceitas).HasColumnName("id_receitas");
            entity.Property(e => e.Calorias)
                .HasColumnType("double(8,2)")
                .HasColumnName("calorias");
            entity.Property(e => e.Carboidratos)
                .HasColumnType("double(8,2)")
                .HasColumnName("carboidratos");
            entity.Property(e => e.FkIdUserReceita).HasColumnName("fk_id_user_receita");
            entity.Property(e => e.Gordura)
                .HasColumnType("double(8,2)")
                .HasColumnName("gordura");
            entity.Property(e => e.Ingredientes)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("ingredientes");
            entity.Property(e => e.ModoPreparo)
                .IsRequired()
                .HasColumnName("modo_preparo");
            entity.Property(e => e.NomeReceita)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nome_receita");
            entity.Property(e => e.Proteinas)
                .HasColumnType("double(8,2)")
                .HasColumnName("proteinas");

            entity.HasOne(d => d.FkIdUserReceitaNavigation).WithMany(p => p.Receita)
                .HasForeignKey(d => d.FkIdUserReceita)
                .HasConstraintName("fk_id_user_receita");
        });

        modelBuilder.Entity<Treino>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("treino")
                .UseCollation("utf8mb4_unicode_ci");

            entity.HasIndex(e => e.FkIdUsuarioTreino, "fk_id_usuario_treino");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Data).HasColumnName("data");
            entity.Property(e => e.DiaTreino)
                .IsRequired()
                .HasColumnType("char(1)")
                .HasMaxLength(1)
                .IsFixedLength()
                .HasColumnName("dia_treino");
            entity.Property(e => e.Duracao)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("duracao");
            entity.Property(e => e.Exercicios)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("exercicios");
            entity.Property(e => e.FkIdUsuarioTreino).HasColumnName("fk_id_usuario_treino");
            entity.Property(e => e.Frequencia)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("frequencia");
            entity.Property(e => e.NomeTreino)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nome_treino");
            entity.Property(e => e.Objetivo)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("objetivo");
            entity.Property(e => e.Repeticoes).HasColumnName("repeticoes");
            entity.Property(e => e.Series).HasColumnName("series");
            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("tipo");

            entity.HasOne(d => d.FkIdUsuarioTreinoNavigation).WithMany(p => p.Treinos)
                .HasForeignKey(d => d.FkIdUsuarioTreino)
                .HasConstraintName("treino_ibfk_1");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("users")
                .UseCollation("utf8mb4_unicode_ci");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Altura)
                .HasColumnType("double(8,2)")
                .HasColumnName("altura");
            entity.Property(e => e.DataNasc).HasColumnName("data_nasc");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.Meta)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("meta");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password");
            entity.Property(e => e.Peso)
                .HasColumnType("double(8,2)")
                .HasColumnName("peso");
            entity.Property(e => e.Sexo)
                .HasMaxLength(255)
                .HasColumnName("sexo");
            entity.Property(e => e.Sobrenome)
                .HasMaxLength(255)
                .HasColumnName("sobrenome");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}