// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dietsync.Models;

#nullable disable

namespace dietsyncapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("dietsync.Models.Contador", b =>
                {
                    b.Property<int?>("Contador1")
                        .HasColumnType("int")
                        .HasColumnName("contador");

                    b.ToTable("contador", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("dietsync.Models.DadosSessao", b =>
                {
                    b.Property<ulong>("IdLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id_login");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("IdLogin"));

                    b.Property<DateTime?>("DataLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("data_login");

                    b.Property<ulong?>("FkIdUserLogin")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("fk_id_user_login");

                    b.HasKey("IdLogin")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkIdUserLogin" }, "fk_id_user_login");

                    b.ToTable("dados_sessao", (string)null);
                });

            modelBuilder.Entity("dietsync.Models.Dieta", b =>
                {
                    b.Property<ulong>("IdDieta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id_dieta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("IdDieta"));

                    b.Property<string>("Alimentos")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("alimentos")
                        .UseCollation("utf8mb4_bin");

                    b.Property<double>("Calorias")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("calorias");

                    b.Property<double>("Carboidratos")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("carboidratos");

                    b.Property<string>("DataDieta")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("data_dieta")
                        .IsFixedLength();

                    b.Property<ulong?>("FkIdUsuarioDieta")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("fk_id_usuario_dieta");

                    b.Property<double>("Gorduras")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("gorduras");

                    b.Property<string>("NomeDieta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_dieta");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<double>("Proteinas")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("proteinas");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<string>("Refeicao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("refeicao");

                    b.Property<string>("TipoDieta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tipo_dieta");

                    b.HasKey("IdDieta")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkIdUsuarioDieta" }, "dietas_ibfk_1");

                    b.ToTable("dietas", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("dietsync.Models.Evolucao", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("altura");

                    b.Property<double>("Cintura")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("cintura");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<ulong?>("FkIdEvolucaos")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("fk_id_evolucaos");

                    b.Property<long>("FkIdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_id_usuario");

                    b.Property<double>("Peso")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("peso");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkIdEvolucaos" }, "fk_id_evolucaos");

                    b.ToTable("evolucaos", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("dietsync.Models.Receitum", b =>
                {
                    b.Property<ulong>("IdReceitas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id_receitas");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("IdReceitas"));

                    b.Property<double>("Calorias")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("calorias");

                    b.Property<double>("Carboidratos")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("carboidratos");

                    b.Property<ulong?>("FkIdUserReceita")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("fk_id_user_receita");

                    b.Property<double>("Gordura")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("gordura");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredientes");

                    b.Property<string>("ModoPreparo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("modo_preparo");

                    b.Property<string>("NomeReceita")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_receita");

                    b.Property<double>("Proteinas")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("proteinas");

                    b.HasKey("IdReceitas")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkIdUserReceita" }, "fk_id_user_receita");

                    b.ToTable("receita", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("dietsync.Models.Treino", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("DiaTreino")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("dia_treino")
                        .IsFixedLength();

                    b.Property<string>("Duracao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("duracao");

                    b.Property<string>("Exercicios")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercicios");

                    b.Property<ulong?>("FkIdUsuarioTreino")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("fk_id_usuario_treino");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("frequencia");

                    b.Property<string>("NomeTreino")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_treino");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("objetivo");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int")
                        .HasColumnName("repeticoes");

                    b.Property<int>("Series")
                        .HasColumnType("int")
                        .HasColumnName("series");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkIdUsuarioTreino" }, "fk_id_usuario_treino");

                    b.ToTable("treino", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("dietsync.Models.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("altura");

                    b.Property<DateOnly>("DataNasc")
                        .HasColumnType("date")
                        .HasColumnName("data_nasc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("meta");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<double>("Peso")
                        .HasColumnType("double(8,2)")
                        .HasColumnName("peso");

                    b.Property<string>("Sexo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sexo");

                    b.Property<string>("Sobrenome")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sobrenome");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("users", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("dietsync.Models.DadosSessao", b =>
                {
                    b.HasOne("dietsync.Models.User", "FkIdUserLoginNavigation")
                        .WithMany("DadosSessaos")
                        .HasForeignKey("FkIdUserLogin")
                        .HasConstraintName("fk_id_user_login");

                    b.Navigation("FkIdUserLoginNavigation");
                });

            modelBuilder.Entity("dietsync.Models.Dieta", b =>
                {
                    b.HasOne("dietsync.Models.User", "FkIdUsuarioDietaNavigation")
                        .WithMany("Dieta")
                        .HasForeignKey("FkIdUsuarioDieta")
                        .HasConstraintName("dietas_ibfk_1");

                    b.Navigation("FkIdUsuarioDietaNavigation");
                });

            modelBuilder.Entity("dietsync.Models.Evolucao", b =>
                {
                    b.HasOne("dietsync.Models.User", "FkIdEvolucaosNavigation")
                        .WithMany("Evolucaos")
                        .HasForeignKey("FkIdEvolucaos")
                        .HasConstraintName("fk_id_evolucaos");

                    b.Navigation("FkIdEvolucaosNavigation");
                });

            modelBuilder.Entity("dietsync.Models.Receitum", b =>
                {
                    b.HasOne("dietsync.Models.User", "FkIdUserReceitaNavigation")
                        .WithMany("Receita")
                        .HasForeignKey("FkIdUserReceita")
                        .HasConstraintName("fk_id_user_receita");

                    b.Navigation("FkIdUserReceitaNavigation");
                });

            modelBuilder.Entity("dietsync.Models.Treino", b =>
                {
                    b.HasOne("dietsync.Models.User", "FkIdUsuarioTreinoNavigation")
                        .WithMany("Treinos")
                        .HasForeignKey("FkIdUsuarioTreino")
                        .HasConstraintName("treino_ibfk_1");

                    b.Navigation("FkIdUsuarioTreinoNavigation");
                });

            modelBuilder.Entity("dietsync.Models.User", b =>
                {
                    b.Navigation("DadosSessaos");

                    b.Navigation("Dieta");

                    b.Navigation("Evolucaos");

                    b.Navigation("Receita");

                    b.Navigation("Treinos");
                });
#pragma warning restore 612, 618
        }
    }
}
